site_title: "Özel İstanbul Cerrahi Hastanesi"
phone: "0212 296 94 50"
whatsapp: "+90 531 650 76 57"
email: "info@istanbulcerrahi.com.tr"
address: "Fulya, Ferah Sokağı No: 22, 34365 Şişli / İstanbul"
instagram: "https://www.instagram.com/istanbulcerrahihastanesi/"
facebook: "https://www.facebook.com/istanbulcerrahihastanesi"
youtube: "https://www.youtube.com/@istanbulcerrahi"
